[relabel]
allow-unauthenticated = [
    "C-*",
    "O-*",
    "S-*",
    "stable-nominated",
]

[autolabel."S-waiting-on-review"]
new_pr = true

[assign]
contributing_url = "https://github.com/rust-lang/libc/blob/HEAD/CONTRIBUTING.md"

[assign.owners]
"*" = [
    "@JohnTitor",
    "@tgross35",
]

[mentions."src/unix/bsd/netbsdlike/openbsd"]
message = "Some changes occurred in OpenBSD module"
cc = ["@semarie"]

[mentions."src/unix/bsd/netbsdlike/mod.rs"]
message = "Some changes occurred in OpenBSD module"
cc = ["@semarie"]

[mentions."src/unix/solarish"]
message = "Some changes occurred in solarish module"
cc = ["@jclulow", "@pfmooney"]

[shortcut]
