variables:
  - group: secrets
resources:
  repositories:
    - repository: rustinfra
      type: github
      name: rust-lang/simpleinfra
      endpoint: gnzlbg
trigger: ["auto-libc","try"]
pr: ["master"]

jobs:
  - job: DockerSwitch
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: azure-install-rust.yml
      - bash: LIBC_CI=1 sh ./ci/run-docker.sh switch
        displayName: Execute run-docker.sh
