name: CI (bors)

on:
  push:
    branches:
      - auto-libc
      - try

jobs:
  docker_linux_tier1:
    name: Docker Linux Tier1
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        target: [
          i686-unknown-linux-gnu,
          x86_64-unknown-linux-gnu,
        ]
    steps:
      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        run: TARGET=${{ matrix.target }} sh ./ci/install-rust.sh
      - name: Execute run-docker.sh
        run: LIBC_CI=1 sh ./ci/run-docker.sh ${{ matrix.target }}

  docker_linux_tier2:
    name: Docker Linux Tier2
    needs: [docker_linux_tier1, style_check]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      max-parallel: 12
      matrix:
        target: [
          aarch64-linux-android,
          aarch64-unknown-linux-gnu,
          aarch64-unknown-linux-musl,
          arm-linux-androideabi,
          arm-unknown-linux-gnueabihf,
          arm-unknown-linux-musleabihf,
          # FIXME: Disabled because currently broken, see:
          # https://github.com/rust-lang/libc/issues/1591
          # asmjs-unknown-emscripten,
          i686-linux-android,
          i686-unknown-linux-musl,
          mips-unknown-linux-gnu,
          mips-unknown-linux-musl,
          # FIXME: Somehow failed on CI
          # https://github.com/rust-lang/libc/runs/1659882216
          # mips64-unknown-linux-gnuabi64,
          # mips64el-unknown-linux-gnuabi64,
          mipsel-unknown-linux-musl,
          powerpc-unknown-linux-gnu,
          powerpc64-unknown-linux-gnu,
          powerpc64le-unknown-linux-gnu,
          s390x-unknown-linux-gnu,
          riscv64gc-unknown-linux-gnu,
          # FIXME: Figure out why this is disabled.
          #wasm32-wasi,
          sparc64-unknown-linux-gnu,
          wasm32-unknown-emscripten,
          x86_64-linux-android,
          x86_64-unknown-linux-gnux32,
          x86_64-unknown-linux-musl,
          # FIXME: It seems some items in `src/unix/mod.rs`
          # aren't defined on redox actually.
          # x86_64-unknown-redox,
        ]
    steps:
      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        run: TARGET=${{ matrix.target }} sh ./ci/install-rust.sh
      - name: Execute run-docker.sh
        run: LIBC_CI=1 sh ./ci/run-docker.sh ${{ matrix.target }}

  build_channels_linux:
    name: Build Channels Linux
    needs: docker_linux_tier2
    runs-on: ubuntu-20.04
    env:
      OS: linux
    strategy:
      fail-fast: true
      max-parallel: 5
      matrix:
        toolchain: [
          stable,
          beta,
          nightly,
          1.13.0,
          1.19.0,
          1.24.0,
          1.25.0,
          1.30.0,
        ]
    steps:
      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        run: TOOLCHAIN=${{ matrix.toolchain }} sh ./ci/install-rust.sh
      - name: Execute build.sh
        run: LIBC_CI=1 TOOLCHAIN=${{ matrix.toolchain }} sh ./ci/build.sh

  # These jobs doesn't actually test anything, but they're only used to tell
  # bors the build completed, as there is no practical way to detect when a
  # workflow is successful listening to webhooks only.
  #
  # ALL THE PREVIOUS JOBS NEED TO BE ADDED TO THE `needs` SECTION OF THIS JOB!

  end_success:
    name: bors build finished
    if: github.event.pusher.name == 'bors' && success()
    runs-on: ubuntu-20.04
    needs: [
      docker_linux_tier1,
      docker_linux_tier2,
      build_channels_linux,
    ]

    steps:
      - name: Mark the job as successful
        run: exit 0

  end_failure:
    name: bors build finished
    if: github.event.pusher.name == 'bors' && (failure() || cancelled())
    runs-on: ubuntu-20.04
    needs: [
      docker_linux_tier1,
      docker_linux_tier2,
      build_channels_linux,
    ]

    steps:
      - name: Mark the job as a failure
        run: exit 1
