name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  docker_linux_tier2:
    permissions:
      actions: write # to cancel workflows (rust-lang/simpleinfra/github-actions/cancel-outdated-builds)
      contents: read # to fetch code (actions/checkout)

    name: Docker Linux Tier2
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      max-parallel: 12
      matrix:
        target: [
          aarch64-linux-android,
          arm-linux-androideabi,
          i686-linux-android,
          x86_64-linux-android,
        ]
    steps:
      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@HEAD
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: TARGET=${{ matrix.target }} sh ./ci/install-rust.sh
      - name: Execute run-docker.sh
        run: LIBC_CI=1 sh ./ci/run-docker.sh ${{ matrix.target }}
